### ISSUE TITLE
segmentation fault trying to upload to an axiom bucket

### ISSUE THREAD

**Issue by andrewljohnson** [axiom-org/axiom#1]
> ➜  src axiom create-bucket gaia-gps-gear-planner 1
> logged into alpha network as 0x40e864f1ae0f9f304ce4dbf94a748cc0c1f9681f9b1bd3fc87c6377695a6ae2081d5
> created bucket:
> { magnet: '',
>   name: 'www:gaia-gps-gear-planner',
>   owner:
>    '0x40e864f1ae0f9f304ce4dbf94a748cc0c1f9681f9b1bd3fc87c6377695a6ae2081d5',
>   providers:
>    [ { available: 0, buckets: null, capacity: 0, id: 1, owner: '' },
>      { available: 0, buckets: null, capacity: 0, id: 2, owner: '' },
>      { available: 0, buckets: null, capacity: 0, id: 3, owner: '' },
>      { available: 0, buckets: null, capacity: 0, id: 4, owner: '' } ],
>   size: 1 }
> ➜  src mkdir gaia-gps-gear-planner
> ➜  src cd gaia-gps-gear-planner
> ➜  gaia-gps-gear-planner touch index.html
> ➜  gaia-gps-gear-planner sub index.html 
> ➜  gaia-gps-gear-planner axiom upload . gaia-gps-gear-planner
> creating torrent...
> [1]    40222 segmentation fault  axiom upload . gaia-gps-gear-planner
>

**Comment by lacker** [comment]
Hmm. This sounds like a problem within the WebTorrent dependency, since the Axiom CLI codebase itself is just javascript/typescript and wouldn't seg fault. Do downloads work, could you try downloading the www:counter bucket?

**Comment by andrewljohnson** [comment]
Same sort of error on download:

> ➜  src axiom download counter
> downloading magnet:?xt=urn:btih:379326fa0b25c472256613aff3dfb313ee0ff3b4&dn=.&tr=ws%3A%2F%2F0.alphatest.network%3A4000&tr=ws%3A%2F%2F1.alphatest.network%3A4000&tr=ws%3A%2F%2F2.alphatest.network%3A4000&tr=ws%3A%2F%2F3.alphatest.network%3A4000 to www:counter
> [1]    57386 segmentation fault  axiom download counter

**Comment by lacker** [comment]
Could you try running:

`DEBUG=webtorrent* axiom download www:counter`

That will turn on debug logging for the webtorrent dependency, which I suspect of being the source of this seg fault.

**Comment by andrewljohnson** [comment]
Seems hung on this output:

> ➜  src DEBUG=webtorrent* axiom download www:counter
> downloading magnet:?xt=urn:btih:379326fa0b25c472256613aff3dfb313ee0ff3b4&dn=.&tr=ws%3A%2F%2F0.alphatest.network%3A4000&tr=ws%3A%2F%2F1.alphatest.network%3A4000&tr=ws%3A%2F%2F2.alphatest.network%3A4000&tr=ws%3A%2F%2F3.alphatest.network%3A4000 to www:counter
>   webtorrent [2d57573] new webtorrent (peerId 2d5757303030332d3570725762626e4a4e723467, nodeId c569a42fd22f6d167c47d4778e378913050878af, port 0) +0ms
>   webtorrent:tcp-pool create tcp pool (port 0) +0ms
>   webtorrent [2d57573] add +6ms
>   webtorrent:torrent [2d57573] [379326f] new torrent +0ms
>   webtorrent [2d57573] listening +1ms
>   webtorrent:torrent [2d57573] [379326f] add peer 104.197.68.5:34551 +609ms
>   webtorrent:peer new tcpOutgoing Peer 104.197.68.5:34551 +0ms
>   webtorrent:torrent [2d57573] [379326f] _drain numConns 0 maxConns 55 +0ms
>   webtorrent:torrent [2d57573] [379326f] drain (2 queued, 0/55 peers) +0ms
>   webtorrent:torrent [2d57573] [379326f] tcp connect attempt to 104.197.68.5:34551 +0ms
>   webtorrent:torrent [2d57573] [379326f] add peer 35.225.45.45:46169 +58ms
>   webtorrent:peer new tcpOutgoing Peer 35.225.45.45:46169 +58ms
>   webtorrent:torrent [2d57573] [379326f] _drain numConns 0 maxConns 55 +0ms
>   webtorrent:torrent [2d57573] [379326f] drain (3 queued, 0/55 peers) +0ms
>   webtorrent:torrent [2d57573] [379326f] tcp connect attempt to 35.225.45.45:46169 +0ms
>   webtorrent:torrent [2d57573] [379326f] add peer 35.238.104.237:45593 +1ms
>   webtorrent:peer new tcpOutgoing Peer 35.238.104.237:45593 +1ms
>   webtorrent:torrent [2d57573] [379326f] _drain numConns 0 maxConns 55 +0ms
>   webtorrent:torrent [2d57573] [379326f] drain (4 queued, 0/55 peers) +0ms
>   webtorrent:torrent [2d57573] [379326f] tcp connect attempt to 35.238.104.237:45593 +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +0ms
>   webtorrent:torrent [2d57573] [379326f] add peer 35.225.45.45:32827 +0ms
>   webtorrent:peer new tcpOutgoing Peer 35.225.45.45:32827 +0ms
>   webtorrent:torrent [2d57573] [379326f] _drain numConns 0 maxConns 55 +0ms
>   webtorrent:torrent [2d57573] [379326f] drain (5 queued, 0/55 peers) +0ms
>   webtorrent:torrent [2d57573] [379326f] tcp connect attempt to 35.225.45.45:32827 +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:46169) +16ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.238.104.237:45593) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +23ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:46169) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.238.104.237:45593) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +55ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +93ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.238.104.237:45593) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:46169) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +23ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:46169) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.238.104.237:45593) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +57ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.238.104.237:45593) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:46169) +0ms
>

**Comment by lacker** [comment]
Wait, so before it seg faulted but now it just hangs?

**Comment by andrewljohnson** [comment]
Now it's back to segfaulting.

> ➜  src DEBUG=webtorrent* axiom download www:counter
> downloading magnet:?xt=urn:btih:379326fa0b25c472256613aff3dfb313ee0ff3b4&dn=.&tr=ws%3A%2F%2F0.alphatest.network%3A4000&tr=ws%3A%2F%2F1.alphatest.network%3A4000&tr=ws%3A%2F%2F2.alphatest.network%3A4000&tr=ws%3A%2F%2F3.alphatest.network%3A4000 to www:counter
>   webtorrent [2d57573] new webtorrent (peerId 2d5757303030332d3570725762626e4a4e723467, nodeId c569a42fd22f6d167c47d4778e378913050878af, port 0) +0ms
>   webtorrent:tcp-pool create tcp pool (port 0) +0ms
>   webtorrent [2d57573] add +6ms
>   webtorrent:torrent [2d57573] [379326f] new torrent +0ms
>   webtorrent [2d57573] listening +1ms
>   webtorrent:torrent [2d57573] [379326f] add peer 104.197.68.5:34551 +609ms
>   webtorrent:peer new tcpOutgoing Peer 104.197.68.5:34551 +0ms
>   webtorrent:torrent [2d57573] [379326f] _drain numConns 0 maxConns 55 +0ms
>   webtorrent:torrent [2d57573] [379326f] drain (2 queued, 0/55 peers) +0ms
>   webtorrent:torrent [2d57573] [379326f] tcp connect attempt to 104.197.68.5:34551 +0ms
>   webtorrent:torrent [2d57573] [379326f] add peer 35.225.45.45:46169 +58ms
>   webtorrent:peer new tcpOutgoing Peer 35.225.45.45:46169 +58ms
>   webtorrent:torrent [2d57573] [379326f] _drain numConns 0 maxConns 55 +0ms
>   webtorrent:torrent [2d57573] [379326f] drain (3 queued, 0/55 peers) +0ms
>   webtorrent:torrent [2d57573] [379326f] tcp connect attempt to 35.225.45.45:46169 +0ms
>   webtorrent:torrent [2d57573] [379326f] add peer 35.238.104.237:45593 +1ms
>   webtorrent:peer new tcpOutgoing Peer 35.238.104.237:45593 +1ms
>   webtorrent:torrent [2d57573] [379326f] _drain numConns 0 maxConns 55 +0ms
>   webtorrent:torrent [2d57573] [379326f] drain (4 queued, 0/55 peers) +0ms
>   webtorrent:torrent [2d57573] [379326f] tcp connect attempt to 35.238.104.237:45593 +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +0ms
>   webtorrent:torrent [2d57573] [379326f] add peer 35.225.45.45:32827 +0ms
>   webtorrent:peer new tcpOutgoing Peer 35.225.45.45:32827 +0ms
>   webtorrent:torrent [2d57573] [379326f] _drain numConns 0 maxConns 55 +0ms
>   webtorrent:torrent [2d57573] [379326f] drain (5 queued, 0/55 peers) +0ms
>   webtorrent:torrent [2d57573] [379326f] tcp connect attempt to 35.225.45.45:32827 +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:46169) +16ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.238.104.237:45593) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +23ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:46169) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.238.104.237:45593) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +55ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +93ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.238.104.237:45593) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:46169) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +23ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:46169) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.238.104.237:45593) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:32827) +57ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (104.197.68.5:34551) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.238.104.237:45593) +0ms
>   webtorrent:torrent [2d57573] [379326f] ignoring peer: duplicate (35.225.45.45:46169) +0ms
> ^C
> ➜  src rm -rf www:counter 
> ➜  src axiom download www:counter
> downloading magnet:?xt=urn:btih:379326fa0b25c472256613aff3dfb313ee0ff3b4&dn=.&tr=ws%3A%2F%2F0.alphatest.network%3A4000&tr=ws%3A%2F%2F1.alphatest.network%3A4000&tr=ws%3A%2F%2F2.alphatest.network%3A4000&tr=ws%3A%2F%2F3.alphatest.network%3A4000 to www:counter
> [1]    61223 segmentation fault  axiom download www:counter
> ➜  src rm -rf www:counter
> ➜  src DEBUG=webtorrent* axiom download www:counter
> downloading magnet:?xt=urn:btih:379326fa0b25c472256613aff3dfb313ee0ff3b4&dn=.&tr=ws%3A%2F%2F0.alphatest.network%3A4000&tr=ws%3A%2F%2F1.alphatest.network%3A4000&tr=ws%3A%2F%2F2.alphatest.network%3A4000&tr=ws%3A%2F%2F3.alphatest.network%3A4000 to www:counter
>   webtorrent [2d57573] new webtorrent (peerId 2d5757303030332d494f4a414c723646634c5038, nodeId 490c7e2c6f56538bef8354fd7d6972d7d56174b4, port 0) +0ms
>   webtorrent:tcp-pool create tcp pool (port 0) +0ms
>   webtorrent [2d57573] add +5ms
>   webtorrent:torrent [2d57573] [379326f] new torrent +0ms
>   webtorrent [2d57573] listening +1ms
> [1]    61277 segmentation fault  DEBUG=webtorrent* axiom download www:counter
>

**Comment by lacker** [comment]
Sounds like this is fixed with the fix for dependencies' Node 12 support
