### ISSUE TITLE
CLI isn't recognizing the "signup" command

### ISSUE THREAD

**Issue by awinchell26** [axiom-org/axiom#11]
I just tried a fresh install of the axiom CLI on Windows 10 and later on Ubuntu running in a VM. In both cases I tried to run the "axiom signup {email}" command and got hit with a usage response. "axiom which" works fine although the CLI does not recognize the commands signup, status, login, etc. I saw in the docs that  Windows might not be fully supported, although this should work in the Ubuntu VM right?

**Comment by lacker** [comment]
Sorry, the documentation is way out of date here. I need to fix it up. There isn't an equivalent of "sign up" right now because you don't need a faucet to operate the most recent version.

**Comment by awinchell26** [comment]
Ah makes, sense, I'll give it a go without the faucet then. Thanks!
