### ISSUE TITLE
can't install axiom-cli on my Mac running Node 12

### ISSUE THREAD

**Issue by andrewljohnson** [axiom-org/axiom#2]
Output from using Yarn (1.16.0) and npm (12.3.1).

Yarn:

> Andrews-MacBook-Pro:src andrewjohnson$ yarn global add axiom-cli
> yarn global v1.16.0
> [1/4] 🔍  Resolving packages...
> warning axiom-cli > webtorrent-hybrid > create-torrent > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
> warning axiom-cli > @material-ui/core > recompose > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
> warning axiom-cli > parcel-bundler > htmlnano > uncss > jsdom > left-pad@1.3.0: use String.prototype.padStart()
> [2/4] 🚚  Fetching packages...
> error wrtc@0.3.7: The engine "node" is incompatible with this module. Expected version "6.x || 8.x || 10.x || 11.x". Got "12.3.1"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

npm:

> Andrews-MacBook-Pro:src andrewjohnson$ npm install -g axiom-cli
> 
> npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
> 
> npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
> 
> npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
> 
> /usr/local/bin/axiom -> /usr/local/lib/node_modules/axiom-cli/build/node/node/cli-main.js
> 
> 
> 
> > fsevents@1.2.9 install /usr/local/lib/node_modules/axiom-cli/node_modules/fsevents
> 
> > node install
> 
> 
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download 
> 
> [fsevents] Success: "/usr/local/lib/node_modules/axiom-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote
> 
> 
> 
> > deasync@0.1.15 install /usr/local/lib/node_modules/axiom-cli/node_modules/deasync
> 
> > node ./build.js
> 
> 
> 
> `darwin-x64-node-12` exists; testing
> 
> Binary is fine; exiting
> 
> 
> 
> > bufferutil@4.0.1 install /usr/local/lib/node_modules/axiom-cli/node_modules/bufferutil
> 
> > node-gyp-build
> 
> 
> 
> 
> 
> > utf-8-validate@5.0.2 install /usr/local/lib/node_modules/axiom-cli/node_modules/utf-8-validate
> 
> > node-gyp-build
> 
> 
> 
> 
> 
> > wrtc@0.3.7 install /usr/local/lib/node_modules/axiom-cli/node_modules/wrtc
> 
> > node scripts/install.js
> 
> 
> 
> Searching for a pre-built wrtc binary
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download 
> 
> node-pre-gyp ERR! install error 
> 
> node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.7/Release/node-v72-darwin-x64.tar.gz
> 
> node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/axiom-cli/node_modules/node-pre-gyp/lib/install.js:139:27)
> 
> node-pre-gyp ERR! stack     at Request.emit (events.js:205:15)
> 
> node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/axiom-cli/node_modules/request/request.js:1066:10)
> 
> node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:200:13)
> 
> node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:573:23)
> 
> node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
> 
> node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:460:22)
> 
> node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:200:13)
> 
> node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:290:12)
> 
> node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:271:11)
> 
> node-pre-gyp ERR! System Darwin 17.7.0
> 
> node-pre-gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/lib/node_modules/axiom-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
> 
> node-pre-gyp ERR! cwd /usr/local/lib/node_modules/axiom-cli/node_modules/wrtc
> 
> node-pre-gyp ERR! node -v v12.3.1
> 
> node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> 
> node-pre-gyp ERR! not ok 
> 
> 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.7/Release/node-v72-darwin-x64.tar.gz
> 
> Unable to install a pre-built wrtc binary; falling back to ncmake
> 
> Running ncmake configure
> 
> CMake binary could not be found. Please verify your PATH.
> 
> /usr/local/lib/node_modules/axiom-cli/node_modules/wrtc/scripts/install.js:51
> 
>     throw new Error('ncmake configure failed for wrtc');
> 
>     ^
> 
> 
> 
> Error: ncmake configure failed for wrtc
> 
>     at build (/usr/local/lib/node_modules/axiom-cli/node_modules/wrtc/scripts/install.js:51:11)
> 
>     at download (/usr/local/lib/node_modules/axiom-cli/node_modules/wrtc/scripts/install.js:40:5)
> 
>     at Object.<anonymous> (/usr/local/lib/node_modules/axiom-cli/node_modules/wrtc/scripts/install.js:67:3)
> 
>     at Module._compile (internal/modules/cjs/loader.js:774:30)
> 
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
> 
>     at Module.load (internal/modules/cjs/loader.js:641:32)
> 
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
> 
>     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
> 
>     at internal/main/run_main_module.js:17:11
> 
> npm ERR! code ELIFECYCLE
> 
> npm ERR! errno 1
> 
> npm ERR! wrtc@0.3.7 install: `node scripts/install.js`
> 
> npm ERR! Exit status 1
> 
> npm ERR! 
> 
> npm ERR! Failed at the wrtc@0.3.7 install script.
> 
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> 
> 
> npm ERR! A complete log of this run can be found in:
> 
> npm ERR!     /Users/andrewjohnson/.npm/_logs/2019-05-26T14_15_50_548Z-debug.log

**Comment by andrewljohnson** [comment]
I tried to install wrtc directly and got weird logs, not sure if it installed. I tried to install axiom-cli again and it didn't work after this.

> Andrews-MacBook-Pro:src andrewjohnson$ npm install wrtc
> ^[⸨       ░░░░░░░░░░░⸩ ⠹ extract:wrtc: verb lock using /Users/andrewjohnson/.npm/_locks/staging-0a66f338f5bb66c5.lock for /Users/an^[⸨       ░░░░░░░░░░░⸩ ⠹ extract:wrtc: verb lock using /Users/andrewjohnson/.npm/_locks/staging-0a66f338f5bb66c5.lock for /Users/an^[⸨       ░░░░░░░░░░░⸩ ⠹ extract:wrtc: verb lock using /Users/andrewjohnson/.npm/_locks/staging-0a66f338f5bb66c5.lock for /Users/an^[⸨       ░░░░░░░░░░░⸩ ⠹ extract:wrtc: verb lock using /Users/andrewjohnson/.npm/_locks/staging-0a66f338f5bb66c5.lock for /Users/an^[⸨       ░░░░░░░░░░░⸩ ⠹ extract:wrtc: verb lock using /Users/andrewjohnson/.npm/_locks/staging-0a66f338f5bb66c5.lock for /Users/an^[⸨            ░░░░░░⸩ ⠏ refresh-package-json:minimist: sill refresh-package-json /Users/andrewjohnson/src/node_modules/readable-st
> > wrtc@0.4.1 install /Users/andrewjohnson/src/node_modules/wrtc
> > node scripts/download-prebuilt.js
> 
> ^[^[^[node-pre-gyp WARN Using needle for node-pre-gyp https download 
> ^[^[^[^[^[^[^[^[^[^[^[[wrtc] Success: "/Users/andrewjohnson/src/node_modules/wrtc/build/Release/wrtc.node" is installed via remote
> ^[npm WARN saveError ENOENT: no such file or directory, open '/Users/andrewjohnson/src/package.json'
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN enoent ENOENT: no such file or directory, open '/Users/andrewjohnson/src/package.json'
> npm WARN src No description
> npm WARN src No repository field.
> npm WARN src No README data
> npm WARN src No license field.
> 
> + wrtc@0.4.1
> added 69 packages from 27 contributors and audited 98 packages in 8.383s
> found 0 vulnerabilities
>

**Comment by lacker** [comment]
With yarn, it looks like you are using Node 12, which isn't compatible with this version of the wrtc dependency. The current version of wrtc does claim to have Node 12 support, though, so it should be possible to update the dependency. It isn't a direct dependency, so I'll have to trace it back.

**Comment by lacker** [comment]
Okay, I changed the dependencies around so that the newest version of the CLI - 0.0.17 - depends on the version of wrtc which alleges to support node 12. Can you try reinstalling 0.0.17 and seeing if that works for you?

**Comment by andrewljohnson** [comment]
To reinstall, do I need to do anything besides npm install -g axiom-cli?
ᐧ

**Comment by lacker** [comment]
Try `npm uninstall -g axiom-cli` followed by `npm install -g axiom-cli`

**Comment by ericvicenti** [comment]
I'm seeing the same issue unfortunately, with node 12.1 on my mac:

```
> yarn global add axiom-cli
...
error wrtc@0.3.7: The engine "node" is incompatible with this module. Expected version "6.x || 8.x || 10.x || 11.x". Got "12.1.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by lacker** [comment]
@ericvicenti Are you installing version 0.0.17 of axiom-cli? It should have an explicit dependency on wrtc 0.4.1 rather than 0.3.7 now.

I updated the title bc it seems like this cluster of issues is Node 12 related

**Comment by ericvicenti** [comment]
I just ran the command again and it still complains about `0.3.7`. Heres yarns verbose output:

https://gist.github.com/ericvicenti/1f3fc88f9698dd6aae1aaa0313c559db

**Comment by lacker** [comment]
Okay, I thought I had a workaround to make `webtorrent-hybrid` use `wrtc@0.4.1` but it was just installing them both. I think I need to get the library upstream to update for node 12 support, I opened an issue with them at https://github.com/webtorrent/webtorrent-hybrid/issues/99

**Comment by lacker** [comment]
@andrewljohnson @ericvicenti OK the wrtc-0.3.7-dependency problem is fixed upstream, it should only require 0.4.1 now. Can you guys try again? `axiom-cli@0.0.19` is the newer, fixed version

**Comment by andrewljohnson** [comment]
Partial success - I was able to install with yarn now. 

I get a different error than before with npm, but I suspect it relates to idiosyncrasies in my brew/npm installs?

> Andrews-MacBook-Pro:src andrewjohnson$ sudo npm install -g axiom-cli
> Password:
> npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
> npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
> npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
> /usr/local/Cellar/node/12.3.1/bin/axiom -> /usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/build/node/node/cli-main.js
> 
> > fsevents@1.2.9 install /usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents
> > node install
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download 
> node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.9 and node@8.16.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 
> node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/lib' 
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/andrewjohnson/.node-gyp/8.16.0"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/.node-gyp"
> gyp WARN install got an error, rolling back install
> gyp WARN install got an error, rolling back install
> gyp ERR! configure error 
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/.node-gyp'
> gyp ERR! System Darwin 17.7.0
> gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
> gyp ERR! cwd /usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents
> gyp ERR! node -v v8.16.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.3.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> node-pre-gyp ERR! System Darwin 17.7.0
> node-pre-gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents
> node-pre-gyp ERR! node -v v8.16.0
> node-pre-gyp ERR! node-pre-gyp -v v0.12.0
> node-pre-gyp ERR! not ok 
> Failed to execute '/usr/local/Cellar/node/12.3.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
> 
> > deasync@0.1.15 install /usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/deasync
> > node ./build.js
> 
> `darwin-x64-node-8` exists; testing
> Binary is fine; exiting
> 
> > bufferutil@4.0.1 install /usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/bufferutil
> > node-gyp-build
> 
> 
> > utf-8-validate@5.0.2 install /usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/utf-8-validate
> > node-gyp-build
> 
> 
> > wrtc@0.4.1 install /usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/wrtc
> > node scripts/download-prebuilt.js
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download 
> node-pre-gyp ERR! install error 
> node-pre-gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/wrtc/build'
> node-pre-gyp ERR! System Darwin 17.7.0
> node-pre-gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/.bin/node-pre-gyp" "install"
> node-pre-gyp ERR! cwd /usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/wrtc
> node-pre-gyp ERR! node -v v8.16.0
> node-pre-gyp ERR! node-pre-gyp -v v0.13.0
> node-pre-gyp ERR! not ok 
> EACCES: permission denied, mkdir '/usr/local/Cellar/node/12.3.1/lib/node_modules/axiom-cli/node_modules/wrtc/build'
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/axiom-cli/node_modules/fsevents):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! wrtc@0.4.1 install: `node scripts/download-prebuilt.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the wrtc@0.4.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/andrewjohnson/.npm/_logs/2019-06-03T16_44_29_291Z-debug.log
>

**Comment by lacker** [comment]
`user "root" does not have permission to access the dev dir "/Users/andrewjohnson/.node-gyp/8.16.0"`

That's pretty weird. How does user root not have permission to do something like that on your system?

Can you try just installing `wrtc@0.4.1`?

**Comment by ericvicenti** [comment]
You fixed it for me. I'm on to the next steps!

**Comment by andrewljohnson** [comment]
I got the install to work on npm now too, by adding --unsafe-perm to the install command. 

    sudo npm install -g axiom-cli --unsafe-perm

It seems like using nvm would solve it too, this relates to some issue with node-gyp: https://github.com/nodejs/node-gyp/issues/454#issuecomment-315691803

Seems reasonable to me to close this issue!

**Comment by lacker** [comment]
Okay, I will close it. These dependencies are pretty annoying - I tried using a tool to bundle it all up for an independent executable, but it did not "just work" because these hard-to-install dependencies are also hard-to-bundle.
