### ISSUE TITLE
Hanging on upload

### ISSUE THREAD

**Issue by ericvicenti** [axiom-org/axiom#3]
Following the guide and things are working until the upload, where it hashes the content and hangs. It has been running for ~5 minutes so far.. not sure if that is expected. If it is, please put a message saying how long it is expected to take! Usually I wouldn't be this patient..

```
Eric-MBP:~ ericvicenti$ axiom login
logging into alpha network...
please enter your passphrase: *****************************************
hello. your public key is 0xa249dec7ba91db78b422309866a0be3e7e41b6c5a7a140db573531784fdfbc4b6604
Eric-MBP:~ ericvicenti$ 
Eric-MBP:~ ericvicenti$ 
Eric-MBP:~ ericvicenti$ axiom create-bucket evv-test 5
logged into alpha network as 0xa249dec7ba91db78b422309866a0be3e7e41b6c5a7a140db573531784fdfbc4b6604
created bucket:
{
  magnet: '',
  name: 'www:evv-test',
  owner: '0xa249dec7ba91db78b422309866a0be3e7e41b6c5a7a140db573531784fdfbc4b6604',
  providers: [
    { available: 0, buckets: null, capacity: 0, id: 1, owner: '' },
    { available: 0, buckets: null, capacity: 0, id: 2, owner: '' },
    { available: 0, buckets: null, capacity: 0, id: 3, owner: '' },
    { available: 0, buckets: null, capacity: 0, id: 4, owner: '' }
  ],
  size: 5
}
Eric-MBP:~ ericvicenti$ mkdir ~/my-cool-example
Eric-MBP:~ ericvicenti$ cd ~/my-cool-example
Eric-MBP:my-cool-example ericvicenti$ echo "hello decentralized world" > index.html
Eric-MBP:my-cool-example ericvicenti$ axiom upload . my-cool-example
creating torrent...
content hash is 9366ba8ed69495f59446ed40a34cc9ed5247aced
```

**Comment by lacker** [comment]
Mmm, that's not it - when I run with a bad bucket name I do get a nicer error, "user x does not own bucket y so cannot update it". The step it's stuck on should just take a moment, I'll investigate more.

**Comment by lacker** [comment]
OK, the most suspicious thing is that there's a non-critical http request sent with no timeout in this codepath. I pushed `axiom-cli@0.0.20` with a fix to this issue - adding a timeout, and also sticking in a log statement. Can you try again with `0.0.20` ? Also use your own bucket name instead of my-cool-example

**Comment by ericvicenti** [comment]
Ah thats it. When I upload the correct bucket, it got to the next step `waiting for host to sync torrent...`, but got stuck there.

After upgrading the CLI to 20, its all fixed and the upload succeeded!

```
Eric-MBP:my-cool-example ericvicenti$ axiom upload . evv-test
creating torrent...
content hash is 9366ba8ed69495f59446ed40a34cc9ed5247aced
waiting for host to sync torrent...
updating blockchain...
logged into alpha network as 0xa249dec7ba91db78b422309866a0be3e7e41b6c5a7a140db573531784fdfbc4b6604
magnet set to magnet:?xt=urn:btih:9366ba8ed69495f59446ed40a34cc9ed5247aced&dn=.&tr=ws%3A%2F%2F0.alphatest.network%3A4000&tr=ws%3A%2F%2F1.alphatest.network%3A4000&tr=ws%3A%2F%2F2.alphatest.network%3A4000&tr=ws%3A%2F%2F3.alphatest.network%3A4000
deploy complete. cleaning up...
Eric-MBP:my-cool-example ericvicenti$ cd ../testdir
Eric-MBP:testdir ericvicenti$ rm -rf ./*
Eric-MBP:testdir ericvicenti$ axiom download evv-test
downloading magnet:?xt=urn:btih:9366ba8ed69495f59446ed40a34cc9ed5247aced&dn=.&tr=ws%3A%2F%2F0.alphatest.network%3A4000&tr=ws%3A%2F%2F1.alphatest.network%3A4000&tr=ws%3A%2F%2F2.alphatest.network%3A4000&tr=ws%3A%2F%2F3.alphatest.network%3A4000 to www:evv-test


^C
Eric-MBP:testdir ericvicenti$ 
Eric-MBP:testdir ericvicenti$ ls
www:evv-test
Eric-MBP:testdir ericvicenti$ ls www\:evv-test/
Eric-MBP:testdir ericvicenti$ 
```

Sadly, the download hangs (the ^C was after ~2 mins)

**Comment by lacker** [comment]
Hmm, the download works pretty fast for me. It seems like this needs a "show increased debug output" option to figure out what else to do. Anyway since the upload is working I am closing this issue. If you can repro a download problem, open an issue, if it's just flaky then I'll consider that to be a feature request not needing an issue per se.
