### ISSUE TITLE
Bucket upload hangs after generating a content hash

### ISSUE THREAD

**Issue by crazyrabbitLTC** [axiom-org/axiom#4]
I am following the Axiom getting started documentation to experiment with buckets. 

The output of the command `axiom create-bucket dennisons-example 1` is: 

```
logged into alpha network as 0xd49281c478ea6a58d63423fd954ed283464a478521c736cdaac8783dc5103dab0d20
created bucket:
{ magnet: '',
  name: 'www:dennisons-example',
  owner:
   '0xd49281c478ea6a58d63423fd954ed283464a478521c736cdaac8783dc5103dab0d20',
  providers:
   [ { available: 0, buckets: null, capacity: 0, id: 1, owner: '' },
     { available: 0, buckets: null, capacity: 0, id: 2, owner: '' },
     { available: 0, buckets: null, capacity: 0, id: 3, owner: '' },
     { available: 0, buckets: null, capacity: 0, id: 4, owner: '' } ],
  size: 1 }
```

I assume the `available: 0` means that there are no providers available. 

Then: `axiom upload . dennisons-example` (after having . created the `hello world` body for an   `index.html` gives me this: 

```
creating torrent...
content hash is c42fbe7e8090e4702c31ec236733805059f673ce
```

This hangs for quite awhile until it finally returns this: 

```
(node:93214) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
```

While in another window: `axiom download dennisons-example` returns: 

```
bucket has no magnet: {"magnet":"","name":"www:dennisons-example","owner":"0xd49281c478ea6a58d63423fd954ed283464a478521c736cdaac8783dc5103dab0d20","providers":[{"available":0,"buckets":null,"capacity":0,"id":1,"owner":""},{"available":0,"buckets":null,"capacity":0,"id":2,"owner":""},{"available":0,"buckets":null,"capacity":0,"id":3,"owner":""},{"available":0,"buckets":null,"capacity":0,"id":4,"owner":""}],"size":1}
```

Any ideas?

**Comment by lacker** [comment]
FWIW the available: 0 doesn't mean there are no providers available, it just means the client didn't fetch that data. Sort of a poor display choice, I will clean that up.

This looks similar to a different issue with the CLI hanging. Are you running version 0.0.20 of the CLI?

**Comment by crazyrabbitLTC** [comment]
Correct, I am running 0.0.20 of the CLI.

**Comment by paulmars** [comment]
I'm getting the same error

**Comment by lacker** [comment]
The MaxListenersExceededWarning isn't indicative of a real problem, that is basically a warning that occurs if the upload runs for long enough. The real problem is just that the upload isn't completing. There's a few reasons this could be happening; I think this CLI needs better logging or a --verbose option in order to figure out what is going wrong.

**Comment by lacker** [comment]
I think I found this problem - the timeout logic was wrong, and it was hanging while trying to communicate with an unresponsive host provider. Give it a try with the new version 0.0.21 of the CLI, and let me know if this works for you.

Also, I added a `-v` or `--verbose` flag to the CLI which will display more logging information. That'll be helpful to debug similar problems in the future. I'll add a suggestion to the template that people provide the verbose output.

**Comment by andrewljohnson** [comment]
I think I have the same problem, even on the latest version 0.0.21,  and the -v/--verbose flag doesn't seem to work AFAICT.

I first tried uploading to a bucket, and it hung.  

     MacBook-Pro:kibbitz andrewjohnson$ axiom upload . kibbitz
     creating torrent...
     content hash is 72be81aea49d7bddc9a788c978e77e3f2ef8fdec

Then I upgraded to 0.0.21 and tried again, but it still seems to hang on creating torrent...

    MacBook-Pro:kibbitz andrewjohnson$ axiom upload . kibbitz
    creating torrent...

I am on node v8.16.0

**Comment by lacker** [comment]
@andrewljohnson If it isn't even generating a content hash, it's not the same problem.

**Comment by andrewljohnson** [comment]
I retract, I was still on 0.0.19 when I got this issue, I had two axioms installed :)

**Comment by lacker** [comment]
I altered the title to be a bit more specific, because I think there are a couple different issues. If anyone is experiencing hangs *after* the CLI prints out a content hash, but before any subsequent logging, in order to debug that I need output from a CLI of at least version 0.0.21, with the `--verbose` flag.

**Comment by paulmars** [comment]
i'm on hotel wifi but here's what i'm getting today. can tether later.

```
success Installed "axiom-cli@0.0.24" with binaries:
```


```
creating torrent...
content hash is d140276f71df926a8104359feb3fc4f10e5c9974
sending prepareUpdateBucket message to ws://0.alphatest.network:4000
warning: error sending prepareUpdateBucket to ws://0.alphatest.network:4000
sending prepareUpdateBucket message to ws://1.alphatest.network:4000
warning: error sending prepareUpdateBucket to ws://1.alphatest.network:4000
sending prepareUpdateBucket message to ws://2.alphatest.network:4000
warning: error sending prepareUpdateBucket to ws://2.alphatest.network:4000
sending prepareUpdateBucket message to ws://3.alphatest.network:4000
warning: error sending prepareUpdateBucket to ws://3.alphatest.network:4000
waiting for host to sync torrent...
warning: connection error to ws://0.alphatest.network:4000
```

**Comment by lacker** [comment]
All four prepareUpdateBucket failing is surprising to me... the webrtc connections fail for weird reasons, but those are just regular http requests. Can you see `http://0.alphatest.network:4000/stats` in a web browser?
