### ISSUE TITLE
CLI hangs immediately after "creating torrent..."

### ISSUE THREAD

**Issue by lacker** [axiom-org/axiom#6]
A couple people have reported that they run:

```
$ axiom upload . bucket-name
creating torrent...
```

And it just hangs without further output. Still happening with CLI version 0.21

**Comment by savil** [comment]
here's the output from running `DEBUG=* axiom upload . my-cool-example-savil`

https://gist.github.com/savil/508a83e632929aaa55904c9ddd82d28b

**Comment by lacker** [comment]
FWIW that debug output is from a successful run, and indeed it looks like the upload worked that time. I'm not totally sure what to do, although it does seem like the `--verbose` flag should do something useful here.

**Comment by lacker** [comment]
Okay, my suspicion is that it failed to get torrent metadata because it couldn't find a non-overloaded tracker at the time. If this happens again, I need to see the output from a failing run of `DEBUG=* axiom upload . my-cool-example-savil`. Specifically, if you grep for the line "content hash is", and it's not in the output, but the line "creating torrent" is in the output, that is a repro of this bug.
