### ISSUE TITLE
User has no account error.

### ISSUE THREAD

**Issue by nandhinianandj** [axiom-org/axiom#9]
**Describe the bug**
A clear and concise description of what the bug is. If it's a CLI bug, run with `--verbose` to log extra information.

**To Reproduce**
1. Run 'axiom upload . mysite'
2. We expect to see 'Success'
3. But we see 'creating torrent...
content hash is 0ac467ecd571669b66825a155c0e867eab5e1e85
sending prepareUpdateBucket message to ws://0.alphatest.network:4000
prepareUpdateBucket successful with ws://0.alphatest.network:4000
sending prepareUpdateBucket message to ws://1.alphatest.network:4000
prepareUpdateBucket successful with ws://1.alphatest.network:4000
sending prepareUpdateBucket message to ws://2.alphatest.network:4000
prepareUpdateBucket successful with ws://2.alphatest.network:4000
sending prepareUpdateBucket message to ws://3.alphatest.network:4000
prepareUpdateBucket successful with ws://3.alphatest.network:4000
waiting for host to sync torrent...
updating blockchain...
logged into alpha network as 0xbe688a5bfafc89ea2b795cc893b4a3edbb161c1da92d942728bd5911bcae8d13c9b6
sending body: e:0xbe688a5bfafc89ea2b795cc893b4a3edbb161c1da92d942728bd5911bcae8d13c9b6:mhN5jV/rJitRsrsYpZ9LUVbUyyp+lfJEeDfMFBwh6r8e5VrLNBUdvsdBUp9gjLN/jcLpHMqbajsbKIKnYYbVCw:{"message":{"account":"0xbe688a5bfafc89ea2b795cc893b4a3edbb161c1da92d942728bd5911bcae8d13c9b6"},"type":"Query"}

Error: cannot perform operation for user 0xbe688a5bfafc89ea2b795cc893b4a3edbb161c1da92d942728bd5911bcae8d13c9b6 that has no account
    at ChainClient.performOperation (/home/anand/.nvm/versions/node/v12.4.0/lib/node_modules/axiom-cli/build/node/iso/ChainClient.js:112:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async ChainClient.updateBucket (/home/anand/.nvm/versions/node/v12.4.0/lib/node_modules/axiom-cli/build/node/iso/ChainClient.js:224:9)
    at async setMagnet (/home/anand/.nvm/versions/node/v12.4.0/lib/node_modules/axiom-cli/build/node/node/cli-main.js:191:5)
    at async upload (/home/anand/.nvm/versions/node/v12.4.0/lib/node_modules/axiom-cli/build/node/node/cli-main.js:217:5)
    at async main (/home/anand/.nvm/versions/node/v12.4.0/lib/node_modules/axiom-cli/build/node/node/cli-main.js:501:9)
exiting due to error
' instead

**For CLI bugs, please provide:**
 - OS: Ubuntu 19.04
 - Node version run `v12.4.0`
 - CLI version. run `0.0.26`

**For API bugs, please provide:**
 - OS: [e.g. macOS 10.14.4]
 - Browser [e.g. Chrome 75.0.3770]
 - `axiom-api` version
 - Chrome extension version

**Additional context**
The commands used for signing up were successful. 
`axiom signup cattykatrina4@gmail.com`
`axiom login`
`axiom status`
Output of status: `logged into alpha network as 0xbe688a5bfafc89ea2b795cc893b4a3edbb161c1da92d942728bd5911bcae8d13c9b6
no account found for user 0xbe688a5bfafc89ea2b795cc893b4a3edbb161c1da92d942728bd5911bcae8d13c9b6
`

**Comment by lacker** [comment]
It looks like you logged into a different account than the one that you ran signup with. Can you try going through signup again and making sure you are logging into the same account?

**Comment by nandhinianandj** [comment]
Yes i am using same token i got on the same email.. could there be a bug in the account to private key mapping, when network is unstable?? Can I delete my account/key and re-create/signup with the same email?
